name: Pull Request with PipeRider
run-name: Pull Request with PipeRider

on:
  pull_request:
    branches:
      - main

jobs:
  piperider-compare:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install DuckDB Binary
        uses: opt-nc/setup-duckdb-action@v1.0.0

      - name: Download source data
        run: make

      - name: PipeRider Compare
        uses: InfuseAI/piperider-compare-action@v1
        with:
          cloud_api_token: ${{ secrets.PIPERIDER_API_TOKEN }}
          cloud_project: ${{ secrets.PIPERIDER_PROJECT }}
          upload: true
