name: pipeirder_ci
run-name: piperider_ci

on:
  pull_request:
    branches:
      - main

jobs:
  piperider-compare:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: PipeRider Compare
        working-directory: ./dbt_kgme
        uses: InfuseAI/piperider-compare-action@v1
        with:
          cloud_api_token: ${{ secrets.PIPERIDER_API_TOKEN }}
          cloud_project: ${{ secrets.PIPERIDER_PROJECT }}
          upload: true
